export const skills = [
  { name: "HTML", icon: "/images/html5-logo.svg" },
  { name: "CSS", icon: "/images/css-logo.svg" },
  { name: "JavaScript", icon: "/images/javascript-logo.svg" },
  { name: "TypeScript", icon: "/images/typescript-logo.svg" },
  { name: "React", icon: "/images/react-logo.svg" },
  { name: "Tailwind CSS", icon: "/images/tailwind-logo.svg" },
  { name: "Dart", icon: "/images/dart-logo.svg" },
  { name: "Flutter", icon: "/images/flutter-logo.svg" },
  { name: "NodeJS", icon: "/images/nodejs-logo.svg" },
  { name: "ASP.NET", icon: "/images/aspnet-logo.svg" },
  { name: "MySQL", icon: "/images/mysql-logo.svg" },
  { name: "MongoDB", icon: "/images/mongodb-logo.svg" },
  { name: "Firebase", icon: "/images/firebase-logo.svg" },
  { name: "Java", icon: "/images/java-logo.svg" },
  { name: "C++", icon: "/images/cpp-logo.svg" },
  { name: "Move", icon: "/images/move-logo.svg" },
  { name: "Solidity", icon: "/images/solidity-logo.svg" },
];
